### ISSUE TITLE
CDDL license and attribution fix-ups

### ISSUE THREAD

**Issue by idodeclare** [omniosorg/pkg5#221]
Hello,

I've noticed some modifications that may need fix-ups to comply with section 3.3 of CDDL, "You may not remove or alter any copyright ... notices contained within the Covered Software, or any notices of licensing or any descriptive text giving attribution to any Contributor ...."

"Covered Software means (a) the Original Software, or (b) Modifications, or (c) the combination of files containing Original Software with files containing Modifications, in each case including portions thereof."

In #203 and #204:

- src/brand/common.ksh, src/brand/poststate, and src/brand/prestate had notices of licensing removed and replaced with an alternative version
- src/brand/shared/firewall.ksh and src/brand/shared/vnic.ksh had source code moved from src/brand/common.ksh but without copying the notices of licensing or attribution to contributors from the original file

In #208:

- src/brand/Makefile.common had source code moved from src/brand/Makefile but without copying the notices of licensing from the original file
- src/brand/etc/Makefile, src/brand/ipkg/Makefile, src/brand/pkgsrc/Makefile had source code moved from src/brand/Makefile but without copying the notices of licensing or attribution to contributors from the original file

**Comment by citrus-it** [comment]
Hi,

Thanks for getting in touch and bringing this to our attention. It does look like a few of the licence notices were changed during the restructure when they should not have been. I will raise some pull requests shortly to revert that in `src/brand/Makefile.common `, `src/brand/common.ksh`, `src/brand/poststate`, and `src/brand/prestate`; thanks again.

The code that was moved over from `common.ksh` into the new `firewall.ksh` and `vnic.ksh` files is solely copyright of the OmniOS Association; the appropriate contributor attribution has been copied over to the new files and we have chosen to adjust the licence notice text at the same time.

`brand/Makefile` was renamed to `brand/Makefile.master` and trimmed down while keeping all of the original attributions, the new `brand/Makefile` and the Makefiles under subdirectories of brand are newly written. I can see that there are a couple of lines in the examples you mention which look the same as lines from the original Makefile, but in this case that is not because they were copied across, just that that's the illumos style.

**Comment by idodeclare** [comment]
Sure no problem.

I'll add some clarification. OmniOS Association originally published the firewall and vnic functions in common.sh, making CDDL 1.9 clause A applicable: "Any file that results from an addition to, deletion from or modification of the contents of a file containing Original Software or previous Modifications...."

"Original Software means the Source Code and Executable form of computer software code that is originally released under this License." common.sh was committed to history in 2008 (now recorded in Git as e4c512f) and presumably was published soon thereafter, becoming Original Software.

Each file in Original Software has an originating author deemed the "Initial Developer" meaning "the individual or entity that first makes Original Software available under this License." The Initial Developer is specially referenced in CDDL 3.3: "You may not remove or alter ... any descriptive text giving attribution to ... the Initial Developer."

Had OmniOS Association originally published the firewall and vnic functions in CDDL 1.9 clause C files, "Any new file that is contributed or otherwise made available under the terms of this License," then OmniOS Association would be the Initial Developer — but that is not the history.

**Comment by jclulow** [comment]
For the functions that were inserted into an existing file, and then inserted also into a new file, I do not believe there is any issue.  None of us are lawyers, but it's reasonably clear that when those functions were written (prior to insertion in a published work) they were owned by the OmniOS folks.  The CDDL doesn't imply Copyright assignment, and as far as I know no other assignment agreement has been undertaken, so they _still_ own that work and have merely chosen to _licence_ it to others.  I would expect that as the original owner of those bits of the code they can relicence or republish them as they see fit, without the CDDL being involved at all -- as many people and corporations have done in the past.

This would obviously be different if OmniOS was _not_ the owner of those changes, and it seems correct in those cases to comply with the licence by leaving notices unaltered, etc.

**Comment by idodeclare** [comment]
@jclulow , there's a party to this whom you're leaving out. That's the original author of common.sh. That entity _licensed_ their intellectual property (as you emphasize), and OmniOS Association made use of that licensed IP to publish a combined work (CDDL 1.9 clause A, "Any file that results from an addition to, deletion from or modification of the contents of a file containing Original Software or previous Modifications.").

The CDDL does apply to "Modifications" of that combined work (CDDL 3.2 Modifications, "The Modifications that You create or to which You contribute are governed by the terms of this License."). Refactoring out functions from a published combined work makes applicable clause B of CDDL 1.9, "Any new file that contains any part of the Original Software or previous Modification...."

As I wrote, "had OmniOS Association originally published the firewall and vnic functions in CDDL 1.9 clause C files, 'Any new file that is contributed or otherwise made available under the terms of this License,' then OmniOS Association would be the Initial Developer [according to the license] — but that is not the history."

That does not mean that anyone but OmniOS Association is the owner of their Modifications. CDDL clearly requires a contributor to "represent that You believe Your Modifications are Your original creation(s) [CDDL 3.2]." This issue is just about compliance with CDDL 3.3 Required Notices.

**Comment by jclulow** [comment]
It would be a CDDL issue if the OmniOS folks were making use of IP they did not own -- because the licence terms would be what grant them the right to use.  Here, though, it's pretty simple: they wrote the code in question, and absent some contract that transfers _ownership_ (e.g., if it was a work made for hire under an employment contract) they are generally free to release that work again and again under different licences.

Critically, we're talking about the functions they wrote themselves.  If _you_ moved that function to another file you would need to abide by the CDDL terms, because you do not own the IP.  Andy wrote them, though, so he doesn't.

That people own their own changes is a pretty key part of why it's so hard to relicence a body of software: you need to collect the permission of each contributor before doing so, or remove the parts of the code they wrote from the software first.
